# Site settings
title: Bigdata Notebook
email: vishnu.viswanath25@gmail.com
description: My blogs in the field of BigData
baseurl:  # the subpath of your site, e.g. /blog/
url:  www.vishnuviswanath.com
twitter_username: #
github_username:  soniclavier
name: Bigdata Notebook
# Build settings
markdown: kramdown

highlighter: pygments

gems :
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"



collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


