# Site settings
title: Bigdata Notebook
email: vishnu.viswanath25@gmail.com
description: My blogs in the field of BigData
baseurl: 
url:  http://www.vishnuviswanath.com
twitter_username: #
github_username:  soniclavier
name: Bigdata Notebook
# Build settings
markdown: kramdown

highlighter: rouge

gems :
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"



collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


