# Site settings
title: Bigdata Notebook
email: vishnu.viswanath25@gmail.com
description: Welcome to my blog where I hope to share my knowledge in the field of Bigdata and Machine learning. I believe any topic if understood properly can be explained in simple terms, and I intend to do so through this blog. 
baseurl: 
url:  http://www.vishnuviswanath.com
twitter_username: #
github_username:  soniclavier
name: Bigdata & ML Notebook
# Build settings
markdown: kramdown

highlighter: rouge

gems :
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"



collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


