# Site settings
title: Hadoop Works
email: vishnu.viswanath25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blogs in the field of BigData
baseurl:  # the subpath of your site, e.g. /blog/
url:  www.vishnuviswanath.com
twitter_username: #
github_username:  soniclavier

# Build settings
markdown: kramdown

highlighter: pygments

gems :
  - jekyll-paginate

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"



collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


